### ISSUE TITLE
ius-dev

### ISSUE THREAD

**Issue by solomongifford** [iusrepo/ius-release#7]
Can the maintainer confirm that ius-dev was removed on purpose?  Some configuration management (salt in particular) enables/disables it and I'd like to know if this was intentional.

**Comment by carlwgeorge** [comment]
It wasn't being used for anything, so we removed it.  Even if we bring it back, it was for a very particular purpose (new packages), so why should that be included in a salt state?  The official way to use IUS is to use the ius-release package, so a salt state to add IUS should just ensure that package is installed (like our [salt example](https://github.com/iuscommunity/automation-examples/blob/saltstack/enable-ius.sls)).  If the state you are using broke because the dev repo went away then it must be managing the repo files directly.  If that is desired for some reason, then I would recommend only managing the stable repo.

**Comment by solomongifford** [comment]
Thanks @carlwgeorge.  The salt official salt state just made sure the dev repo was disabled.  I'll commit a PR to get that removed.
